# Generated by Django 5.0 on 2024-01-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldstemples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temple',
            name='state',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
