# Generated by Django 5.0 on 2024-01-11 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ldstemples', '0002_temple_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temple',
            name='state',
        ),
    ]
